hdf5: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/bin/h5cc conflicts between attempted installs of lib32-hdf5-1.14.2-r0.armv7ahf_neon and hdf5-1.14.2-r0.cortexa57
  file /usr/bin/h5hlcc conflicts between attempted installs of lib32-hdf5-1.14.2-r0.armv7ahf_neon and hdf5-1.14.2-r0.cortexa57

The differences of h5cc are as follows:
@@ -44,7 +44,7 @@
       exit $status
       ;;
     *)
-      /usr/bin/arm-pokymllib32-linux-gnueabi/arm-pokymllib32-linux-gnueabi-clang $@ `pkg-config --define-variable=prefix=$dir --cflags --libs hdf5`
+      /usr/bin/aarch64-poky-linux/aarch64-poky-linux-clang $@ `pkg-config --define-variable=prefix=$dir --cflags --libs hdf5`
       status=$?
       exit $status
       ;;

The differences of h5hlcc are as follows:
@@ -44,7 +44,7 @@
       exit $status
       ;;
     *)
-      /usr/bin/arm-pokymllib32-linux-gnueabi/arm-pokymllib32-linux-gnueabi-clang $@ `pkg-config --define-variable=prefix=$dir --cflags --libs hdf5_hl`
+      /usr/bin/aarch64-poky-linux/aarch64-poky-linux-clang $@ `pkg-config --define-variable=prefix=$dir --cflags --libs hdf5_hl`
       status=$?
       exit $status
       ;;

(From meta-openembedded rev: cf4a2fa949c77ae207af766fde02a6ec5e29a779)

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit fc7666e5bc01ddcdc16d9d3b838be5c35d84fda2)
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Reed Frandsen <rfrandse@us.ibm.com>

Change-Id: Icfd6da33a043b3e5809ac199dab3dd6766301c14