useradd_base: Fix sed command line for passwd-expire
A previous commit tried to add the --follow-symlinks option to
the perform_passwd_expire function in useradd_base.bbclass, however it used
a single -.

This is interpreted as --file=ollow-symlinks which results in...

sed: couldn't open file ollow-symlinks: No such file or directory

and...

ERROR: <image name>: passwd --expire operation did not succeed.

Fix by adding the missing -

(From OE-Core rev: 67721b71bf677097645b9150a31ac833125c0c23)

(From poky rev: dc33087410ae71ca6e2d4ac63ff4c948ac78d495)

Signed-off-by:  Adam Johnston <adam.johnston@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 3c0deafcfcea3f610c7dd9a2d2884a16fbfe0497)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Reed Frandsen <rfrandse@us.ibm.com>

Change-Id: Ie5dd061b2d83c5908447ec293ef43effa2a045b3