lib/oe/path: Deploy files can start only with a dot
There might be only hidden files deployed. In that case we don't need a
generic wildcard present in copy command, otherwise it fails with:

Exception: subprocess.CalledProcessError: Command 'cp -afl --preserve=xattr ./.??* ./* <BUILDDIR>/tmp/deploy/images/qemux86-64' returned non-zero exit status 1.

Subprocess output:
cp: cannot stat './*': No such file or directory

(From OE-Core rev: c45f3e00189e034157996b88103a83efec3e0cf6)

(From poky rev: bdfac04a9f4047e9286a3029064fec3a8b8656e4)

Signed-off-by: Vyacheslav Yurkov <Vyacheslav.Yurkov@wika.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
(cherry picked from commit f92c751281609ea6bd6b838307de4bc70bf26ab9)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Reed Frandsen <rfrandse@us.ibm.com>

Change-Id: I9ac4f10ca85fc3fcb3529c9df580b29618cb7cf0