vpd:Overwrite dummy ECC library with the actual one (#211)
This commit installs the actual ecc library in /usr/lib file system
space, which is overwriting the dummy ecc library installed via meson
from the source repository (openpower-vpd-parser).

This is done intentionally to avoid sharing the actual ecc source code
and instead just share the ecc shared library object.

Test:
Tested on rainier.
Corrupted the base panel vpd and checked with ibm-read-vpd app.
With the original ecc library, the error should be thrown and with the dummy
ecc library, no error will be thrown.

Achieving the expected results.

root@rain111bmc:~# ibm-read-vpd --file /sys/bus/i2c/drivers/at24/7-0050/eeprom
ERROR: ECC check did not pass for the Record:VR10
root@rain111bmc:~#

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>